language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - npm -g install npm@1.x.x
install:
  - npm install -g grunt-cli mocha
  - npm install
  - cd external/amber_cli
  - npm install
  - cd ../..
